🍱asset:
- changed-files:
  - any-glob-to-any-file: ['**/*.avif', '**/*.ico', '**/*.png', '**/*.svg']
🐛bug:
- head-branch: ['^fix', 'fix']
♻️ci:
- changed-files:
  - any-glob-to-any-file: '.github/**/*.yml'
⚙️config:
- changed-files:
  - any-glob-to-any-file: '**/*config.*'
dependencies:
- changed-files:
  - any-glob-to-any-file: ['package-lock.json', '**/package.json']
📝documentation:
- changed-files:
  - any-glob-to-any-file: ['@robopo/docs/**', '**/*.md', '**/*.mdx']
🚀enhancement:
- all:
  - changed-files:
    - any-glob-to-any-file: '@robopo/web/app/**'
🪸git:
- changed-files:
  - any-glob-to-any-file: ['.gitattributes', '**/.gitignore']
🧰infrastructure:
- changed-files:
  - any-glob-to-any-file: ['**/*.toml', '.devcontainer/*', '.editorconfig', 'biome.json']
✅test:
- changed-files:
  - any-glob-to-any-file: ['@robopo/web/happydom.tsx', '@robopo/web/test/**']
🆚vscode:
- changed-files:
  - any-glob-to-any-file: '.vscode/*'
