config:
  MD013:
    line_length: 120
fix: true
gitignore: true
ignores:
  - "@robopo/docs/**"
  - "@robopo/web/README.md"
  - .github/pull_request_template.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - README.md
