name: autofix.ci

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches: main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: 🐣 Setup mise
        uses: jdx/mise-action@v4

      - name: 📦 Update dependencies
        run: mise update

      # - name: Run Biome
      #   run: biome check --write

      - name: Commit
        if: success() || failure()
        uses: autofix-ci/action@v1.3.3
        with:
          commit-message: "fix(autofix.ci): apply automated fixes"
