name: 🔍 Dependency Review

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request_target:

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: 🔍 Dependency Review
        uses: actions/dependency-review-action@v5
        with:
          comment-summary-in-pr: always
